### PR TITLE
Create QuickSort Algorithm.cpp

### PR DESCRIPTION
**Pull request by RiteshKr00**

### CODE REVIEW

**Comment by PrakashGatiyala** [comment]
> _ No description provided. _

Share your issue link

**Comment by RiteshKr00** [comment]
[Issue Link](https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/issues/132)

**Comment by PrakashGatiyala** [comment]
> [Issue Link](https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/issues/132)

**Review by PrakashGatiyala — CHANGES_REQUESTED** [review]
Remove space in the file name. Use _ or - instead of space

**Pull request closed without merging**
