### PR TITLE
Create Bubble sort algo-py

### PR DESCRIPTION
**Pull request by Sambhav250703**
Created Bubble sort algo 

Bubble sort

### CODE REVIEW

**Review by PrakashGatiyala — CHANGES_REQUESTED** [review]
Remove space in file name and share issue link

**Comment by Sambhav250703** [comment]
> Remove space in file name and share issue link

Done required changes

**Comment by PrakashGatiyala** [comment]
> share issue link

share issue link

**Comment by Sambhav250703** [comment]
> > share issue link
> 
> share issue link

https://github.com/scaleracademy/scaler-september-open-source-challenge/issues/186

**Comment by PrakashGatiyala** [comment]
> > > share issue link
> > 
> > 
> > share issue link
> 
> [scaleracademy/scaler-september-open-source-challenge#186](https://github.com/scaleracademy/scaler-september-open-source-challenge/issues/186)

Issued created on this Repo.  You have to share. If you haven't created one, Go ahead and create one.

**Review by PrakashGatiyala — APPROVED** [review]

**Comment by PrakashGatiyala** [comment]
I will merge this PR once you share issue link.

**Comment by Sambhav250703** [comment]
This issue is already there pls check it out

https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/issues/107

**Comment by Sambhav250703** [comment]
I have share the issue link pls merge the Pr

**Pull request merged**
