### PR TITLE
added Binary_search.cpp file

### PR DESCRIPTION
**Pull request by rithwik003**
Signed-off-by: rithwik003 <amaraneni.rithwik@gmail.com>

### CODE REVIEW

**Comment by PrakashGatiyala** [comment]
> Signed-off-by: rithwik003 [amaraneni.rithwik@gmail.com](mailto:amaraneni.rithwik@gmail.com)

Hi @rithwik003 remove space in file name.

**Comment by PrakashGatiyala** [comment]
LGTM!

**Comment by PrakashGatiyala** [comment]
Give me your issue link for this PR.

**Comment by rithwik003** [comment]
The issue link for this PR is https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/issues/112

**Pull request merged**
