### PR TITLE
Added program for partition equal subset sum

### PR DESCRIPTION
**Pull request by krati5**

### CODE REVIEW

**Review by PrakashGatiyala — CHANGES_REQUESTED** [review]
Remove Spaces in file name

**Comment by krati5** [comment]
> Remove Spaces in file name

Hi Prakash, I have made the required changes. Please check.

**Review by PrakashGatiyala — APPROVED** [review]
lgtm!

**Comment by PrakashGatiyala** [comment]
This reference to https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/issues/127

**Pull request merged**
